/** Simple flat job list for the apply form. */
export const jobTypeOptions = [
  "Administrative / Office Assistant",
  "Babysitter / Nanny",
  "Barista",
  "Bookkeeper",
  "Carpenter",
  "Cashier",
  "Cleaner / Janitor",
  "Construction Worker",
  "Cook / Kitchen Staff",
  "Customer Service",
  "Delivery Driver",
  "Dishwasher",
  "Dog Walker / Pet Care",
  "Electrician",
  "Factory Worker",
  "Fast Food Worker",
  "General Laborer",
  "Handyman",
  "Healthcare / Nursing Assistant (CNA)",
  "Housekeeper",
  "HVAC Technician",
  "IT / Tech Support",
  "Landscaper / Gardener",
  "Office / Admin",
  "Painter",
  "Plumber",
  "Receptionist",
  "Retail Sales Associate",
  "Security Guard",
  "Server / Waiter",
  "Truck Driver",
  "Warehouse Worker",
  "Sales / Marketing",
  "Remote / Work From Home",
  "Other",
] as const;
